name: VMware Troubleshooting
favicon: null
layout_spectrum: 0.75229
typography_spectrum: 0.74659
title: VMware Troubleshooting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d6a8e'
    - '#c1ce2f'
    - '#51910d'
    - '#ffffff'
    - '#5d9bb3'
  brandStrength: 1
  lightness: 0.17692109756171703
  saturation: 0.7126989730168134
  rhythmicContrast: 0.07501063542440534
purpose: []
